feat: fetch eth prize pool board on website
fluidity-money/fluidity-app pull request #1348
Opened 2022-11-29 21:30 UTC by harlexkhal

2022-11-29 22:08 UTC, renzroque approved these changes

2022-11-30 04:09 UTC, eli-d requested changes

2022-11-30 04:09 UTC, eli-d commented on web/fluidity.money/src/data/ethereum/prizePool.ts
> +  const provider = new JsonRpcProvider(rpcUrl);
probably want to do this in a loader (i.e. `useCache`) so that the RPC URL isn't public in the client.

2022-11-30 04:09 UTC, eli-d commented on web/fluidity.money/src/data/ethereum/prizePool.ts
> +  const poolAddress: string = "0xD3E24D732748288ad7e016f93B1dc4F909Af1ba0";
maybe source this from `config.toml`

2022-11-30 04:09 UTC, eli-d commented on web/fluidity.money/src/data/ethereum/prizePool.ts
> +const handleContractErrors = async (
this function already exists in `app/util/chainUtils/ethereum/transaction.ts`

2022-11-30 04:09 UTC, eli-d commented on web/fluidity.money/src/data/ethereum/prizePool.ts
> +    return totalPrizePool.toNumber();
imo this should stay as a string or BN the entire time - if there's a lot of decimals precision goes down very fast, and this number is just for display so should be fine as a string

2022-11-30 04:09 UTC, eli-d commented on web/fluidity.money/src/screens/RewardsStats/RewardsStats.tsx
> +    getEthTotalPrizePool(process.env.NEXT_PUBLIC_FLU_ETH_RPC_HTTP)
pretty sure this won't work, `process.env` won't be defined

2022-11-30 10:38 UTC, eli-d approved these changes

2022-11-30 10:49 UTC, merged