sketch out util mining
fluidity-money/fluidity-app pull request #1505
Opened 2022-12-21 01:05 UTC by iscke

2022-12-28 02:34 UTC, af-afk requested changes

2022-12-28 02:34 UTC, af-afk commented on common/ethereum/applications/applications.go
> +		utility = ethereum.AddressFromString("uniswap")
> Debug code left over

2022-12-28 02:34 UTC, af-afk commented on contracts/ethereum/contracts/IUtilityClient.sol
> +    address utility;
Could this be relabelled to fixed bytes? Or a word? Would be good to leave a comment why an address was chosen and that this is possible to be something arbitrary

2022-12-28 02:34 UTC, af-afk commented on contracts/ethereum/contracts/IUtilityClient.sol
> +    function operator_() external returns (address);
Could this be emitted to avoid being leaky since the server doesn't need this info?

2022-12-28 02:34 UTC, af-afk commented on contracts/ethereum/contracts/Operator.sol
> +pragma solidity 0.8.11;
Can we bump this up potentially and keep it consistent with the previous versioning?

2022-12-28 02:34 UTC, af-afk commented on contracts/ethereum/contracts/Operator.sol
> +    event NewUtilityClient(address name, address client);
Clarify the language to eliminate the distinction between "Client" and "Server" if we're not using Utility Mining server

2022-12-28 02:34 UTC, af-afk commented on contracts/ethereum/contracts/Operator.sol
> +        token_ = Token(token);
Might be worth clarifying that the reason for this is due to poor tooling

2022-12-28 02:34 UTC, af-afk commented on contracts/ethereum/contracts/Operator.sol
> +    function addUtilityMiner(
Rename to utility client to keep it consistent?

2022-12-28 02:34 UTC, af-afk commented on contracts/ethereum/contracts/Operator.sol
> +        token_.batchReward(rewards, firstBlock, lastBlock);
Can you add a comment that this will revert if it's bad?

2022-12-28 02:34 UTC, af-afk commented on contracts/ethereum/contracts/Operator.sol
> +        token_.batchReward(rewards, firstBlock, lastBlock);
Any way to have an extra check here? Check if the oracle's calling here

2022-12-28 02:34 UTC, af-afk commented on contracts/ethereum/contracts/Operator.sol
> +            client.utilityMine(utilityRewards[i]);
Maybe worth mentioning what this is doing again and that it'll revert if there's a reason

2023-01-30 01:20 UTC, iscke commented
superseded by #1628

2023-01-30 01:20 UTC, closed without merging