utility mining, take 2
fluidity-money/fluidity-app pull request #1628
Opened 2023-01-24 23:53 UTC by iscke

2023-02-03 01:45 UTC, af-afk requested changes

2023-02-03 01:45 UTC, af-afk commented on cmd/microservice-ethereum-worker-client/util.go
> +func formatPayouts(payouts map[applications.Utility]worker.Payout) string {
Could be String()

2023-02-03 01:45 UTC, af-afk commented on cmd/microservice-ethereum-worker-server/main.go
> +	EnvRegistryAddress = `FLU_ETHEREUM_REGISTRY_ADDR`
Should be renamed to OPERATOR

2023-02-03 01:45 UTC, af-afk commented on cmd/microservice-ethereum-worker-server/main.go
> +			defaultDeltaWeightNum   = big.NewInt(1)
@cibo6 can you make another pass over the math to explain this?

2023-02-03 01:45 UTC, af-afk commented on cmd/microservice-ethereum-worker-server/main.go
> +			defaultDeltaWeightNum   = big.NewInt(1)
Assuming it's the number of seconds in a year

2023-02-03 01:45 UTC, af-afk commented on cmd/microservice-ethereum-worker-server/main.go
> +					fluidClients = []appTypes.Utility{ appTypes.UtilityFluid }
"Formatting is munted"

2023-02-03 01:45 UTC, af-afk commented on cmd/microservice-ethereum-worker-server/main.go
> +					fluidClients = []appTypes.Utility{ appTypes.UtilityFluid }
Can you clarify that we always pay out the FLUID token using this?

2023-02-03 01:45 UTC, af-afk commented on cmd/microservice-ethereum-worker-server/main.go
> +				pools, err, poolErrs := fluidity.GetTrfVars(
Rename to UtilityVars and provide a comment about the lookup context (the pool is the amount you're trying to distribute in Utility Mining)

2023-02-03 01:45 UTC, af-afk commented on cmd/microservice-ethereum-worker-server/main.go
> +					log.Debug(func (k *log.Log) {
Log some way of identifying the pool in logs

2023-02-03 01:45 UTC, af-afk commented on cmd/microservice-ethereum-worker-spooler/main.go
> +			var totalWinAmount float64
Worth noting in your words "this value can be imprecise, this is USD"

2023-02-03 01:45 UTC, af-afk commented on cmd/microservice-ethereum-worker-spooler/main.go
> +			var totalWinAmount float64
Just used for the spooler threshold

2023-02-03 01:45 UTC, af-afk commented on cmd/microservice-solana-worker-server/main.go
> +			pools := []worker_types.PoolDetails{
Worth noting that we mock this internally since our Solana infra is not as mature (owing to the Solend situation)

2023-02-03 01:45 UTC, af-afk commented on common/calculation/probability/payouts.go
> +func CalculatePayoutsCombined(sourcePayouts map[applications.Utility][]worker.Payout, winningBalls int) map[applications.Utility]worker.Payout {
Could this be tested?

2023-02-03 01:45 UTC, af-afk commented on common/calculation/probability/probability.go
> +func calculateBpy(blockTimeRat *big.Rat, pool worker.PoolDetails) *big.Rat {
@cibo6 can you review this code?

2023-02-03 01:45 UTC, af-afk commented on common/calculation/probability/probability.go
> +func WinningChances(gasFee, atx, payoutFreq *big.Rat, distributionPools []worker.PoolDetails, winningClasses, averageTransfersInBlock int, blockTimeInSeconds uint64, emission *worker.Emission) (winni
@cibo6

2023-02-03 01:45 UTC, af-afk commented on common/ethereum/fluidity/registry.go
> +func init() {
"Remove the default, so if we don't support something properly it just breaks"

2023-02-03 01:45 UTC, af-afk commented on contracts/ethereum/contracts/IFluidClient.sol
> +struct TrfVars {
Would be worth to rename this to utility mining configuration

2023-02-03 01:45 UTC, af-afk commented on contracts/ethereum/contracts/Operator.sol
> +    struct ScannedTrfVar {
Needs to be renamed too

2023-02-03 01:45 UTC, af-afk commented on contracts/ethereum/contracts/Operator.sol
> +    string constant FLUID_TOKEN = "FLUID";
"I'm not sure if this needs to be hardcoded, we can probably remove that"

2023-02-03 01:45 UTC, af-afk commented on contracts/ethereum/contracts/Operator.sol
> +            require(
Add a comment about the requirement check here

2023-02-03 01:45 UTC, af-afk commented on contracts/ethereum/contracts/Operator.sol
> +                vars[i].found = false;
Have it revert so it identifies a bug in our code?

2023-02-03 01:45 UTC, af-afk commented on contracts/ethereum/contracts/TestUtilityClient.sol
> +pragma solidity 0.8.11;
Could be moved into a separate "examples" section would be good

2023-02-03 01:45 UTC, af-afk commented on contracts/ethereum/contracts/Token.sol
> +        address _registry
We need to have the registry set up properly that we can call already keyed into everything before we do this deploy

2023-02-03 01:45 UTC, af-afk commented on contracts/ethereum/contracts/Token.sol
> +        address _registry
Should be renamed to _oracle again

2023-02-03 01:45 UTC, af-afk commented on contracts/ethereum/contracts/Token.sol
> +        address _registry
We need to kick off Factory for the new deployments/upgrades

2023-02-03 01:45 UTC, af-afk commented on contracts/ethereum/contracts/Token.sol
> +    function getTrfVars() external returns (TrfVars memory) {
Would need to be renamed

2023-02-03 01:45 UTC, af-afk commented on database/102-up-timescale/20230125112103-spooler_add-utilities.sql
> +	ADD COLUMN utility VARCHAR DEFAULT 'FLUID' NOT NULL,
"Utility name" would be good

2023-02-03 01:45 UTC, af-afk commented on database/102-up-timescale/20230125123154-winners_add-utilities.sql
> +	ADD COLUMN utility VARCHAR DEFAULT 'FLUID' NOT NULL;
Rename to have the new thing

2023-02-03 01:45 UTC, af-afk commented on lib/types/applications/applications.go
> +type Utility string
UtilityName

2023-02-03 01:45 UTC, af-afk commented on lib/types/worker/ethereum.go
> +		SourcePayouts   map[applications.Utility][]Payout `json:"random_payouts"`
Can we rename this to be consistent with the field name?

2023-02-03 01:45 UTC, af-afk commented on lib/types/worker/ethereum.go
> +		SourcePayouts   map[applications.Utility][]Payout `json:"random_payouts"`
"Fluid to one ball to ten cents"

2023-02-03 01:45 UTC, af-afk commented on lib/types/worker/ethereum.go
> +		Utility         applications.Utility       `json:"utility"`
Should be renamed

2023-02-03 01:45 UTC, af-afk commented on lib/types/worker/ethereum.go
> +		UtilityName    applications.Utility     `json:"utility"`
Should be the same

2023-02-03 01:45 UTC, af-afk commented on lib/types/worker/worker.go
> +		ExchangeRate *big.Rat `json:"exchange_rate"`
> "Make sure that's actually correct"

2023-02-06 00:18 UTC, iscke commented
> [af-afk](https://github.com/af-afk) [Feb 3, 2023](https://github.com/fluidity-money/fluidity-app/pull/1628#discussion_r1095261604)

> We need to kick off Factory for the new deployments/upgrades

2023-02-06 06:22 UTC, af-afk approved these changes
Going ahead with this to configure some testing with develop so as to not block code coming in

2023-02-06 06:45 UTC, af-afk approved these changes

2023-02-06 06:46 UTC, merged