Add getTVL function to the Registry
fluidity-money/fluidity-app pull request #1768
Opened 2023-03-10 01:07 UTC by af-afk

2023-03-14 03:27 UTC, iscke approved these changes

2023-03-14 03:28 UTC, iscke requested changes

2023-03-14 03:28 UTC, iscke commented on contracts/ethereum/contracts/Registry.sol
> +            uint256 amount = token.rewardPoolAmount() + token.totalSupply();
oh wait this should just be total supply

2023-03-14 03:29 UTC, iscke commented on contracts/ethereum/contracts/Registry.sol
> +            uint256 amount = token.rewardPoolAmount() + token.totalSupply();
`totalSupply` is the amount of fluid token minted - the amount of base token fluidified

2023-03-16 03:10 UTC, af-afk commented on contracts/ethereum/contracts/Registry.sol
> +            uint256 amount = token.rewardPoolAmount() + token.totalSupply();
The reward pool is the difference in the amount quoted by the underlying tokens and the total supply, so it's also the ctoken that isn't owned by anyone in particular, so the TVL is the prize pool too

2023-03-16 03:40 UTC, iscke approved these changes

2023-03-16 03:42 UTC, merged