sketch out UM boost clients
fluidity-money/fluidity-app pull request #1913
Opened 2023-05-01 07:39 UTC by iscke

2023-05-05 05:29 UTC, af-afk requested changes
Very small nitpicks!

2023-05-05 05:29 UTC, af-afk commented on contracts/ethereum/interfaces/IFluidClient.sol
> +string constant DEFAULT_CALCULATION_TYPE = "";
Could explain what this means with a comment?

2023-05-05 05:29 UTC, af-afk commented on contracts/ethereum/contracts/Registry.sol
> +            if (address(utility) == address(0)) revert("zero utility");
Could explain the context here

2023-05-05 05:29 UTC, af-afk commented on database/101-up-postgres/20230501170526-worker_utility-client-override-vars.sql
> +CREATE TABLE custom_pool_overrides (
It would be good to rename this table to keep it consistent with the other tables (ie, prefix it with "worker_") given the category of the migrtaion

2023-05-05 05:29 UTC, af-afk commented on cmd/microservice-ethereum-worker-server/main.go
> +			return PayoutDetails{}
Isn't this not necessary?

2023-05-05 05:29 UTC, af-afk commented on cmd/microservice-ethereum-worker-server/main.go
> +					"Unhandled calculation type '%s'!",
Could use %#v instead

2023-05-05 05:29 UTC, af-afk commented on cmd/microservice-ethereum-worker-server/main.go
> +			if found {
I think this could be a switch statement to be clearer

2023-05-05 05:29 UTC, af-afk commented on cmd/microservice-ethereum-worker-server/main.go
>  				var (
It's worth noting that these will only be appended to

2023-05-05 05:29 UTC, af-afk commented on cmd/microservice-ethereum-worker-server/main.go
> +						k.Format("Source payouts: %v", payoutDetails.randomSource)
Would be good to have extra context in this log

2023-05-06 02:09 UTC, iscke commented on cmd/microservice-ethereum-worker-server/main.go
> +			return PayoutDetails{}
yeah, golang doesn't know that log.Fatal is terminating

2023-05-06 02:10 UTC, iscke commented on cmd/microservice-ethereum-worker-server/main.go
> +			if found {
there's no other branch

2023-05-06 07:01 UTC, af-afk approved these changes

2023-05-06 07:01 UTC, af-afk commented on cmd/microservice-ethereum-worker-server/main.go
> +			// calculate this one in its own pool
Clarify that this is going into the TRF

2023-05-06 07:01 UTC, af-afk commented on cmd/microservice-ethereum-worker-server/main.go
> +func calculateSpecialPayoutDetails(dbNetwork network.BlockchainNetwork, pool workerTypes.UtilityVars, transferFeeNormal, currentAtx, payoutFreq *big.Rat, winningClasses, btx int, epochTime uint64, em
Also explaining how this works and why it's the way it is with some background in the product decision as well would be good

2023-05-10 00:26 UTC, eli-d approved these changes

2023-05-10 00:26 UTC, eli-d commented on tests/pipeline/docker-compose.yml
> +  test-special-utilitymining:
bruh

2023-05-10 00:27 UTC, eli-d approved these changes

2023-05-10 00:27 UTC, eli-d commented on common/calculation/probability/probability.go
> +	// TODO IS THIS CORRECT
```suggestion
	
```

2023-05-10 00:29 UTC, eli-d approved these changes

2023-05-10 00:29 UTC, eli-d commented on tests/pipeline/docker-compose.yml
> +  contracts-special-utilmining:
```suggestion
  contracts-special-util-mining
```

2023-05-10 01:03 UTC, merged

2023-05-10 13:43 UTC, cibo6 reviewed
looks good