feat: update token.sol to track volume
fluidity-money/fluidity-app pull request #2364
Opened 2023-08-21 00:23 UTC by glo12345

2023-08-21 00:31 UTC, af-afk requested changes

2023-08-21 00:31 UTC, af-afk commented on contracts/ethereum/contracts/LootboxStaking.sol
> +    uint256 private minLockupTime_;
These changes have to be at the bottom of the states due to the upgrade compatibility, and you can't change the constants instead?

2023-08-21 00:31 UTC, af-afk commented on contracts/ethereum/contracts/LootboxStaking.sol
> +    mapping(address => Deposit[]) private deposits_;
Same issue with the other

2023-08-21 00:31 UTC, af-afk commented on contracts/ethereum/contracts/LootboxStaking.sol
> +        uint256 _minLockupTime,
Need a separate function to initialise these variables and need to bump up the version

2023-08-21 00:31 UTC, af-afk commented on contracts/ethereum/contracts/Token.sol
> +    struct EpochVolume {
Can you put the struct outside the scope of this and into an interface? And add documentation explaining what it does? And can you not use a mapping inside the struct?

2023-08-21 00:31 UTC, af-afk commented on contracts/ethereum/contracts/Token.sol
> +        // TODO
Don't leave the comment here

2023-08-21 00:31 UTC, af-afk commented on contracts/ethereum/contracts/Token.sol
> +        // set epoch volume
Maybe you can eliminate some redundancy here

2023-08-21 00:31 UTC, af-afk commented on contracts/ethereum/contracts/Token.sol
> +        uint256 startEpoch = 0;
... same

2023-08-21 00:31 UTC, af-afk commented on contracts/ethereum/contracts/Token.sol
> +    function volume(
Can you make this a part of the interface too?

2023-08-23 03:00 UTC, glo12345 commented
Ditching tracking on-chain to track utility specific volume - migrating to develop-add-trading-comp-leaderboard

2023-08-23 03:00 UTC, closed without merging