fix: add token filtering to arb user-actions
fluidity-money/fluidity-app pull request #2368
Opened 2023-08-25 03:59 UTC by glo12345

2023-08-25 06:18 UTC, owfie approved these changes

2023-09-11 01:21 UTC, eli-d requested changes

2023-09-11 01:21 UTC, eli-d commented on web/app.fluidity.money/app/util/api/graphql.ts
> +        url: "https://a321-2405-6e00-22ec-87d7-62c1-b7c4-60c6-9c4b.ngrok-free.app/v1/graphql",
debug?

2023-09-11 02:56 UTC, eli-d approved these changes

2023-09-11 02:56 UTC, merged