Develop leaderboard page
fluidity-money/fluidity-app pull request #2412
Opened 2023-11-20 06:33 UTC by mariarykova

2024-01-04 01:34 UTC, eli-d requested changes

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/public/assets/fonts/aeonik/Aeonik-Bold.woff
remove all fonts from the repo, there should be a static import (check how app.fluidity.money does this)

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/README.md
> +This is a [Next.js](https://nextjs.org/) project bootstrapped with [`create-next-app`](https://github.com/vercel/next.js/tree/canary/packages/create-next-app).
write a small description of what this does, how to build it, how to use it - remove the boilerplate

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/config.toml
> +[[drivers.ethereum]]
delete this since it's not used

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/cypress/e2e/page.cy.ts
> +      expect(response.body).to.have.length(3);
is this always true?

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/cypress/e2e/spec.cy.ts
> +    cy.visit('https://example.cypress.io')
example test

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/cypress/fixtures/example.json
> +{
example test

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/cypress/support/commands.ts
> +/// <reference types="cypress" />
delete this file if it's not used

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/ethereum.d.ts
> +  ethereum?: any; // Use `any` or a more specific type if available
shouldn't need to use `window.ethereum`

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/package.json
> +    "urql": "^4.0.6",
remove this as a dependency

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/public/assets/wallets/coin98.svg
we should have all the logos we need in static hosting

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/public/next.svg
shouldn't need this

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/public/vercel.svg
don't need this

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/Card/Card.module.scss
fix surfing imports rather than duplicating these

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/ConnectWallet/ConnectWalletModal/ConnectWalletModal.tsx
> +  const [configData, setConfigData] = useState<any>(null);
don't use any type

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/ConnectWallet/ConnectWalletModal/ConnectWalletModal.tsx
> +  const [configData, setConfigData] = useState<any>(null);
don't think this is used, delete it

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/ConnectWallet/ConnectWalletModal/ConnectWalletModal.tsx
> +  }, []);
delete this since config isn't used

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/ConnectWallet/ConnectWalletModal/ConnectWalletModal.tsx
> +              {configData && <EthWalletsMap />}
remove configData here

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/ConnectWallet/ConnectedWallet/ConnectedWallet.tsx
> +type Address = string;
unnecessary since it's only in this file

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/ConnectWallet/ConnectedWallet/ConnectedWallet.tsx
> +const addressSize = 12 / 2;
should just be set to 6, and have a comment as to why

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/ConnectWallet/ConnectedWallet/ConnectedWallet.tsx
> +  const leftSide = address.substring(0, 5);
should use the constant from above?

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/ConnectWallet/ConnectedWallet/ConnectedWallet.tsx
> +        {/*<Jazzicon diameter={36} seed={jsNumberForAddress(address)} />*/}
remove

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/ConnectWallet/ConnectedWalletModal/ConnectedWalletModal.tsx
> +export const ConnectedWalletModal = ({
have this in the same file as connect wallet, and conditionally render

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/ConnectWallet/ConnectedWalletModal/ConnectedWalletModal.tsx
> +    <img height="32" width="32" src="/copyIconCircle.svg" alt="copy" />
have this state be something like `useState<"circle" | "checked" | ...>`, then check the condition when rendering

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/ConnectWallet/ConnectedWalletModal/connectedWalletModal.cy.tsx
> +    cy.contains(trimAddress(props.address)).should("be.visible");
i would hardcode the trimmed address in the test file, since this doesn't really test that it trims correctly

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/Profile/index.tsx
> +            !connectedWalletModalVisibility &&
this is redundant

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/Profile/index.tsx
> +            address={`0x${address}`}
don't think this needs a 0x in front

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/Table/index.tsx
> +  filter: (item: T) => boolean; // eslint-disable-line no-unused-vars
this shouldn't need an eslint tag

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/Table/index.tsx
> +  //  const isTransition = useTransition();
remove

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/Table/index.tsx
> +  const cappedPageCount = Math.min(240, count);
comment why 240

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/Table/index.tsx
> +  const frozenRows = data.filter((row) => freezeRow?.(row));
these should all be memoised (`useMemo`)

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/Table/index.tsx
> +  const handlePageTurn = (page: number) => {
this function doesn't do anything

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/Table/index.tsx
> +              // TODO: need to think what to use instead of useTransition from remix
address this TODO

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/components/Table/index.tsx
> +                .filter((_) => !freezeRow?.(_))
don't name this `_` since that's usually used for unused variables, but here it's being used

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/config.ts
> +export const aeonik = localFont({
use the static fonts rather than local

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/config.ts
> +export const tableHeadings = [
these should be in Table

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/context.tsx
> +import type BN from "bn.js";
take this out of surfing

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/ensName.tsx
> +const UseEnsName = (address: any) => {
don't use the any type

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/ensName.tsx
> +    address: address.address,
address should be passed directly to this hook

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/ensName.tsx
> +    chainId: 1,
don't hardcode the chain (pass it in with a default maybe)

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/favicon.ico
should be static

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/layout.tsx
> +      className={`${inter.className} ${spline.className} ${aeonik.className}`}
remove fonts

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/pages/api/users.ts
> +export default function users(
remove test file

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/pages/api/config.ts
> +import { parse } from "toml";
don't need this file

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/config/webapp.config.server.ts
> +import { parse } from "toml";
don't need this file

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/queries/useLeaderboardRanking.ts
> +      limit: 40
pass limit in as a variable

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/queries/useLeaderboardRanking.ts
> +      limit: 40
pass limit in as a variable

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/queries/useLeaderboardRanking.ts
> +      limit: 40
pass limit in as a variable

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/queries/ChainContext.tsx
> +  leaderboardRanking24Hours: LeaderboardRanking[] | [];
don't need `| []`

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/queries/ChainContext.tsx
> +export type Network = "arbitrum" | "etheruim" | "solana";
ethereum misspelled, also this should exist somewhere else (probably in surfing)

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/queries/ChainContext.tsx
> +  userAddress: string | undefined;
prefer `userAddress?: string`

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/queries/ChainContext.tsx
> +  const [onChainData, setOnChainData] = useState<any>({
don't use any type

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/providers.tsx
> +        projectId: "60cd988a2683be6b1787c53081016310",
make into an environment variable

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/page.tsx
> +export type IRow = React.HTMLAttributes<HTMLDivElement> & {
is this duplicated?

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/page.tsx
> +  const [sortedByItem, setSortedByItem] = useState<string>("number");
maybe make this an enum

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/page.tsx
> +        setSortedData(apiState.leaderboardRanking24Hours);
this could be moved to a closure so it's not repeated below

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/page.tsx
> +        apiState && setSortedData(newArray);
this could be one line `setSortedData([...leaderboard, ...apiState.dataUser24Hours])`

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/page.tsx
> +          //  const leaderboard = newSortedData.map((leaderboardRow, i) => ({
remove

2024-01-04 01:34 UTC, eli-d commented on web/leaderboard/src/app/page.tsx
> +  const [filterIndex, setFilterIndex] = useState(0);
make this more clear (e.g. `useState<"allTime" | "24hour">` or something)

2024-01-15 02:00 UTC, mariarykova commented on web/leaderboard/cypress/support/commands.ts
> +/// <reference types="cypress" />
I left this file but as it is needed for cypress tests running otherwise there was a mistake

2024-01-15 02:00 UTC, mariarykova commented on web/leaderboard/src/app/components/Card/Card.module.scss
can't fix this, still have a problem

2024-01-15 23:57 UTC, af-afk requested changes

2024-01-15 23:57 UTC, af-afk commented on web/leaderboard/sentry.client.config.ts
> +  dsn: "https://02225ae4a93c4b438998f8f56041566b@o1103433.ingest.sentry.io/6130103",
Set this with an environment variable!

2024-01-15 23:57 UTC, af-afk commented on web/leaderboard/sentry.edge.config.ts
> +  dsn: "https://02225ae4a93c4b438998f8f56041566b@o1103433.ingest.sentry.io/6130103",
Environment variable here too!

2024-01-16 03:51 UTC, af-afk approved these changes

2024-01-22 05:10 UTC, merged