Refactor random tier function for clarity. Add simulations.
fluidity-money/fluidity-app pull request #2615
Opened 2024-04-08 14:43 UTC by DrGrooveDev

2024-04-08 14:48 UTC, af-afk requested changes

2024-04-08 14:48 UTC, af-afk commented on cmd/microservice-ethereum-create-transaction-lootboxes/pick-random-tier.go
> +func getExpectedTierPcts() map[int]float64 {
Thank you for this PR @DrGrooveDev! My advice to you is that this looks mostly good, but I'd like to request:
1. Adjust it to use golang's testing library. Use it in tandem with https://pkg.go.dev/github.com/stretchr/testify
2. Move the rest of the test code to another file called _test.go and then follow the rest you'd need for the testing
3. When you assert test this, try with some tolerance! Try to seed the random number generator with something specific for testing optionally (we haven't bothered with this.)
Thank you!

2024-04-09 01:01 UTC, DrGrooveDev commented on cmd/microservice-ethereum-create-transaction-lootboxes/pick-random-tier.go
> +func getExpectedTierPcts() map[int]float64 {
Moved the tests to a new file. Check that they integrate correctly in the build. I'm still having some issues with my environment, so I needed to do some funky stuff to get Go to run unit tests.

The unit test runs 10 million draws then compares the results to the expected values. It uses a tolerance of +/- 0.5% for the Asserts.

Implementation note: I chose not to implement the test with a fixed seed. rand.Seed(seedValue) is deprecated. We can still used a fixed seed if necessary, but that would involve passing a rand instance to the getExpectedTierPcts(). Production code would use a random seed, test code would pass the fixed seed. This seemed like unnecessary complexity just for the unit test, so I opted not to. Lmk if you want it done like this though.
![image](https://github.com/fluidity-money/fluidity-app/assets/166350737/3d879912-08da-46b7-ac98-56018d564756)

2024-04-10 12:45 UTC, af-afk requested changes

2024-04-10 12:45 UTC, af-afk commented on cmd/microservice-ethereum-create-transaction-lootboxes/pick-random-tier_test.go
> +	fmt.Printf("\n")
Remove the use of fmt generally, and have it so that if it HAS to log, it does so using https://pkg.go.dev/testing#T.Log.

2024-04-10 12:45 UTC, af-afk commented on cmd/microservice-ethereum-create-transaction-lootboxes/pick-random-tier_test.go
> +		assert.True(t, thisResult >= float64(acceptableLow) && thisResult <= float64(acceptableHigh), fmt.Sprintf("Tier %v value is not within expected range", i))
Break this up into informative variable use so it's clear how this breaks down, and maybe some description of how it works too I would say.

2024-04-19 16:15 UTC, merged

2024-04-19 16:15 UTC, af-afk commented
Thanks for this @DrGrooveDev !